import logoIcon from '../assets/images/logo.png';
import logoIconBig from '../assets/images/logo-big.png';
import eyeIcon from '../assets/images/icon-eye.png';
import eyeSlashIcon from '../assets/images/eye-2.png';
import codeSend from '../assets/images/code-send.png';
import editIcon from '../assets/images/icon-edit.svg';
import editIconBig from '../assets/images/icon-edit-big.png';
import tickIcon from '../assets/images/tick-mark.png';
import dotIcon from '../assets/images/dots.png';
import filterIcon from '../assets/images/filter.png';
import clockIcon from '../assets/images/clock.png';
import imageIcon from '../assets/images/image.png';
import delIcon from '../assets/images/icon-delete.svg';
import deleteIcon from '../assets/images/delete-big.png';
import profileIcon from '../assets/images/icon-my-profile.png';
import passwordIcon from '../assets/images/icon-password.png';
import signoutIcon from '../assets/images/icon-signout.png';
import calendarIcon from '../assets/images/calendar.png';
import dragIcon from '../assets/images/drag-img.png';
import refreshIcon from '../assets/images/Refresh.svg';
import errorIcon from '../assets/images/error.png';
import minusIcon from '../assets/images/minu-circle.png';
import sortIcon from '../assets/images/sort-icon.png';
import tickIconbig from '../assets/images/dummy/state-3.png';
import plusCircleIcon from '../assets/images/plus-circle.png';
import closeBlackIcon from '../assets/images/close-black.png';
import closeWhiteIcon from '../assets/images/close-white.png';
import filterNoneIcon from '../assets/images/filter-none.png';
import logoutIcon from '../assets/images/icon-logout.png';
import dashboardIcon from '../assets/images/empty-dashboard.png';
import bigClockIcon from '../assets/images/big-clock.png';
import smallcicleIcon from '../assets/images/sm-circle.png';
import dragsmIcon from '../assets/images/drag-imges.png';
import minusGrey from '../assets/images/minus-grey.png';
import plusGrey from '../assets/images/plus-grey.png';
import resetIcon from '../assets/images/reset.png';
import makeIcon from '../assets/images/make-cover.png';
import cardDefault from '../assets/images/card-defualt.png';
import errorImage from '../assets/images/Error-404.png';
import profileDefault from '../assets/images/profile-defualt.png';
import tickIconsm from '../assets/images/sm-tik.png';
import leftArrowIcon from '../assets/images/left-arrow.png';
import ArrowLeftIcon from '../assets/images/arrow-left.svg';
import stretchTo from '../assets/images/img-mode/stretch-to.png';
import fillCenter from '../assets/images/img-mode/fill-center.png';
import fitWithin from '../assets/images/img-mode/fit-within.png';
import staticCrop from '../assets/images/img-mode/static-crop.png';
import stretchToView from '../assets/images/img-mode/stretch-to-view.png';
import fillCenterBig from '../assets/images/img-mode/fill-center-big.png';
import fullImg from '../assets/images/img-mode/full-img.png';
import flip from '../assets/images/aug-mode/flip.png';
import rotate from '../assets/images/aug-mode/rotate.png';
import randomCrop from '../assets/images/aug-mode/random-crop.png';
import randomCropBig from '../assets/images/img-mode/random-crop-big.png';
import rotation from '../assets/images/aug-mode/rotation.png';
import blur from '../assets/images/aug-mode/blur.png';
import greyscale from '../assets/images/aug-mode/greyscale.png';
import randomErasing from '../assets/images/aug-mode/random-erasing.png';
import colorJitter from '../assets/images/aug-mode/color-Jitter.png';
import noise from '../assets/images/aug-mode/noise.png';
import JpegCompression from '../assets/images/aug-mode/jpeg-compression.png';
import correctFlower from '../assets/images/aug-mode/correct-flower.png';
import noiseImg from '../assets/images/aug-mode/noise-img.png';
import erasingBig from '../assets/images/img-mode/random-erasing.png';
import infoIcon from '../assets/images/info-icon.png';
import iconSetting from '../assets/images/icons-setting.svg';
import crossWhite from '../assets/images/cross-white.svg';
import dropDown from '../assets/images/down-arrow.png';
import { number } from 'yup';
import { NumberLimit } from './number';


export const LOGO_ICON = logoIcon;
export const LOGO_ICON_BIG = logoIconBig;
export const EYE_ICON = eyeIcon;
export const EYE_SLASH_ICON = eyeSlashIcon;
export const CODE_SEND = codeSend;
export const EDIT_ICON = editIcon;
export const EDIT_ICON_BIG = editIconBig;
export const TICK_ICON = tickIcon;
export const DOT_ICON = dotIcon;
export const DROP_DOWN = dropDown;
export const FILTER_ICON = filterIcon;
export const CLOCK_ICON = clockIcon;
export const IMAGE_ICON = imageIcon;
export const DEL_ICON = delIcon;
export const DELETE_ICON = deleteIcon;
export const PROFILE_ICON = profileIcon;
export const PROFILE_DEFAULT = profileDefault;
export const PASSWORD_ICON = passwordIcon;
export const SIGNOUT_ICON = signoutIcon;
export const CALENDAR_ICON = calendarIcon;
export const DRAG_IMG = dragIcon;
export const ERROR_ICON = errorIcon;
export const MINUS_ICON = minusIcon;
export const SORT_ICON = sortIcon;
export const TICK_ICON_BIG = tickIconbig;
export const PLUS_CIRCLE_ICON = plusCircleIcon;
export const CLOSE_BLACK = closeBlackIcon;
export const CLOSE_WHITE = closeWhiteIcon;
export const FILTER_NONE_ICON = filterNoneIcon;
export const LOGOUT_ICON = logoutIcon;
export const DASHBOARD_EMPTY = dashboardIcon;
export const BIG_CLOCK = bigClockIcon;
export const SMALL_CIRCLE = smallcicleIcon;
export const DRAG_IMGES = dragsmIcon;
export const MINUS_GREY = minusGrey;
export const PLUS_GREY = plusGrey;
export const RESET_ICON = resetIcon;
export const MAKE_ICON = makeIcon;
export const PROJECT_EMPTY = cardDefault;
export const ErrorImage = errorImage;
export const TICK_ICON_SM = tickIconsm;
export const LEFT_ARROW_ICON = leftArrowIcon;
export const ARROW_LEFT_ICON = ArrowLeftIcon;
export const STRETCH_TO = stretchTo;
export const FILL_CENTER = fillCenter;
export const FIT_WITHIN = fitWithin;
export const STATIC_CROP = staticCrop;
export const STRETCH_TO_VIEW = stretchToView;
export const FILL_CENTER_BIG = fillCenterBig;
export const FULL_IMG = fullImg;
export const FILP = flip;
export const ROTATE = rotate;
export const RANDOM_CROP = randomCrop;
export const RANDOM_CROP_BIG = randomCropBig;
export const ROTATION = rotation;
export const BLUR = blur;
export const GREYSCALE = greyscale;
export const RANDOM_ERASING = randomErasing;
export const COLOR_JITTER = colorJitter;
export const NOISE = noise;
export const JCOMPRESSION = JpegCompression;
export const CORRECT_FLOWER = correctFlower;
export const NOISE_IMG = noiseImg;
export const ERASING_BIG = erasingBig;
export const INFO_ICON = infoIcon;
export const ICON_SETTING = iconSetting;
export const CROSS_WHITE = crossWhite;
export const REFRESH_ICON = refreshIcon;
export const noiseImagePath = (imgNum: number) => {
    imgNum = Math.ceil(imgNum / NumberLimit.FOUR);
    return `/noise/noise_${imgNum}.png`;
};

